import {
  KeywordDrawSource,
  KeywordLotteryStatus,
  KeywordPrizeType,
  type KeywordLotteryRow,
} from './types';

export const mockKeywordLotteryList: KeywordLotteryRow[] = [
  {
    id: '1',
    drawSource: KeywordDrawSource.LiveSession,
    liveSession: '週五晚間直播',
    sessionName: '週五晚場 - 母親節抽好禮',
    keyword: 'A+1',
    startAt: '2026-05-09 20:00:00',
    endAt: '2026-05-09 22:30:00',
    starFilter: null,
    prizeType: KeywordPrizeType.Product,
    prizeContent: '玻尿酸保濕面膜 5 入',
    cart: '預設購物車',
    autoDraw: false,
    winnerCount: 3,
    status: KeywordLotteryStatus.InProgress,
    createdAt: '2026-05-01 10:21:00',
  },
  {
    id: '2',
    drawSource: KeywordDrawSource.DateRange,
    liveSession: '',
    sessionName: '',
    keyword: 'GET',
    startAt: '2026-05-12 21:00:00',
    endAt: '2026-05-12 23:00:00',
    starFilter: null,
    prizeType: KeywordPrizeType.Points,
    prizeContent: '100 點',
    cart: '預設購物車',
    autoDraw: false,
    winnerCount: 5,
    status: KeywordLotteryStatus.NotStarted,
    createdAt: '2026-05-05 14:08:00',
  },
  {
    id: '3',
    drawSource: KeywordDrawSource.LiveSession,
    liveSession: '週六加碼直播',
    sessionName: '週六加碼場',
    keyword: '抽我抽我',
    startAt: '2026-04-26 14:00:00',
    endAt: '2026-04-26 17:00:00',
    starFilter: 4,
    prizeType: KeywordPrizeType.Product,
    prizeContent: '小幫手限定徽章組',
    cart: '主購物車',
    autoDraw: true,
    winnerCount: 1,
    status: KeywordLotteryStatus.Drawn,
    createdAt: '2026-04-20 09:45:00',
  },
  {
    id: '4',
    drawSource: KeywordDrawSource.DateRange,
    liveSession: '',
    sessionName: '貼文回饋場',
    keyword: '+1',
    startAt: '2026-05-15 12:00:00',
    endAt: '2026-05-20 23:59:59',
    starFilter: null,
    prizeType: KeywordPrizeType.Points,
    prizeContent: '50 點',
    cart: '預設購物車',
    autoDraw: false,
    winnerCount: 10,
    status: KeywordLotteryStatus.NotStarted,
    createdAt: '2026-05-10 16:30:00',
  },
  {
    id: '5',
    drawSource: KeywordDrawSource.LiveSession,
    liveSession: '週日午茶直播',
    sessionName: '',
    keyword: 'YA',
    startAt: '2026-05-08 19:00:00',
    endAt: '2026-05-08 21:30:00',
    starFilter: null,
    prizeType: KeywordPrizeType.Product,
    prizeContent: '冷萃黑咖啡 6 入',
    cart: '預設購物車',
    autoDraw: false,
    winnerCount: 2,
    status: KeywordLotteryStatus.Ended,
    createdAt: '2026-05-02 11:00:00',
  },
];
