import { library } from '@fortawesome/fontawesome-svg-core'

// live-order / live-records 等 live-commerce 原本就用 fas 的圖示維持 solid。
import {
  faArrowRightArrowLeft,
  faArrowUpRightFromSquare,
  faBullhorn as faBullhornSolid,
  faChevronLeft as faChevronLeftSolid,
  faCircleCheck as faCircleCheckSolid,
  faCircleDollarToSlot,
  faCommentDots,
  faCommentMedical,
  faCube,
  faHashtag as faHashtagSolid,
  faInbox,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faPen as faPenSolid,
  faPenToSquare,
  faPlus,
  faReply,
  faSearch,
  faShuffle as faShuffleSolid,
  faSortDown,
  faTag,
  faTrash as faTrashSolid,
} from '@fortawesome/free-solid-svg-icons'
import {
  faComment as faCommentRegular,
  faCommentDots as faCommentDotsRegular,
  faEdit as faEditRegular,
  faEye as faEyeRegular,
  faPenToSquare as faPenToSquareRegular,
  faUser as faUserRegular,
} from '@fortawesome/free-regular-svg-icons'

// 後台 header / sidebar 等 portal-vue 風格的 layout 走 Pro kit 的 regular（線框版）。
import {
  faAngleRight,
  faBagShopping,
  faBan,
  faBell,
  faBoxIsometric,
  faBuildingUser,
  faBullhorn,
  faChartMixed,
  faChartTreeMap,
  faChevronDown,
  faChevronLeft,
  faCircleCheck,
  faCirclePause,
  faCirclePlay,
  faCircleQuestion,
  faClipboardList,
  faComment as faCommentProRegular,
  faDollarSign,
  faEnvelope,
  faEnvelopeOpen,
  faEye,
  faFileCirclePlus,
  faFileInvoiceDollar,
  faGear,
  faGift,
  faGlobe,
  faHashtag,
  faListRadio,
  faMoon,
  faPen,
  faReceipt,
  faRightFromBracket,
  faShop,
  faShuffle,
  faSunBright,
  faTags,
  faTrash,
  faUser,
  faUsers,
  faVideo,
} from '@awesome.me/kit-979923bcd0/icons/classic/regular'

// 平台品牌圖示（Facebook / Instagram）走 Pro kit brands。
import {
  faFacebook,
  faInstagram,
  faTiktok,
} from '@awesome.me/kit-979923bcd0/icons/classic/brands'

/**
 * 集中註冊本專案會用到的 FontAwesome icon；新元件用新 icon 時請補進來。
 *
 * 同名同 prefix（如 solid faChevronLeft 與 regular faChevronLeft）會以**後加入者覆蓋**前者，
 * 而 layout 元件指定 `['far', 'X']`、live-order 多半 `['fas', 'X']`，因此實際靠 prefix 分流；
 * 重複註冊 solid/regular 同名 icon 是安全的——前提是 imports 用 alias 區分（faBullhornSolid vs faBullhorn）。
 */
library.add(
  // fas — live-commerce 原本就用的
  faArrowRightArrowLeft,
  faArrowUpRightFromSquare,
  faBullhornSolid,
  faChevronLeftSolid,
  faCircleCheckSolid,
  faCircleDollarToSlot,
  faCommentDots,
  faCommentMedical,
  faCube,
  faHashtagSolid,
  faInbox,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faPenSolid,
  faPenToSquare,
  faPlus,
  faReply,
  faSearch,
  faShuffleSolid,
  faSortDown,
  faTag,
  faTrashSolid,
  // far（free）— 少數 portal-vue 原本就用 regular 的
  faCommentRegular,
  faCommentDotsRegular,
  faEditRegular,
  faEyeRegular,
  faPenToSquareRegular,
  faUserRegular,
  // far（Pro kit）— layout 用的線框版
  faAngleRight,
  faBagShopping,
  faBan,
  faBell,
  faBoxIsometric,
  faBuildingUser,
  faBullhorn,
  faChartMixed,
  faChartTreeMap,
  faChevronDown,
  faChevronLeft,
  faCircleCheck,
  faCirclePause,
  faCirclePlay,
  faCircleQuestion,
  faClipboardList,
  faCommentProRegular,
  faDollarSign,
  faEnvelope,
  faEnvelopeOpen,
  faEye,
  faFileCirclePlus,
  faFileInvoiceDollar,
  faGear,
  faGift,
  faGlobe,
  faHashtag,
  faListRadio,
  faMoon,
  faPen,
  faReceipt,
  faRightFromBracket,
  faShop,
  faShuffle,
  faSunBright,
  faTags,
  faTrash,
  faUser,
  faUsers,
  faVideo,
  // fab（Pro kit brands）— 平台識別圖示
  faFacebook,
  faInstagram,
  faTiktok,
)
