/**
 * 得標清單頁專用的 FontAwesome icon 註冊（prototype 版）。
 *
 * 來源 portal 用 FA Pro 的 `far`（線框）；prototype 只有 free 套件，
 * 故頁面模板已將 `['far', X]` 統一改為 `['fas', X]`（solid），
 * 平台品牌 icon 用 free-brands 的 `fab`。此檔集中 library.add，
 * 由 main.ts 以 side-effect import 一次即可。
 */
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowLeft,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsUpDown,
  faBan,
  faBell,
  faBox,
  faCartShopping,
  faCheckDouble,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleQuestion,
  faClock,
  faCopy,
  faEdit,
  faFileImport,
  faFileSignature,
  faHashtag,
  faMagnifyingGlass,
  faMinus,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotateLeft,
  faShuffle,
  faTriangleExclamation,
  faTruck,
  faTruckFast,
  faUser,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import {
  faFacebook,
  faInstagram,
  faLine,
  faTiktok,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faArrowDown,
  faArrowLeft,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsUpDown,
  faBan,
  faBell,
  faBox,
  faCartShopping,
  faCheckDouble,
  faChevronDown,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleQuestion,
  faClock,
  faCopy,
  faEdit,
  faFileImport,
  faFileSignature,
  faHashtag,
  faMagnifyingGlass,
  faMinus,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotateLeft,
  faShuffle,
  faTriangleExclamation,
  faTruck,
  faTruckFast,
  faUser,
  faXmark,
  faFacebook,
  faInstagram,
  faLine,
  faTiktok,
)
